### ISSUE TITLE
Optimization idea

### ISSUE THREAD

**Issue by ankur6ue** [neuml/cord19q#3]
in etl.execute.py        
for _, text in sections:
            # Look for at least one keyword match
            if re.findall(regex, text.lower()):
                tags = "COVID-19"

if we find a "COVID-19" tag, we should return? No need to look through the other sentences?

Also, in execute.files, good to add a check for key not present in the dictionary:
        if row.get('has_pmc_xml_parse'):
            if row["has_pmc_xml_parse"].lower() == "true":

Thanks so much for making this code public. Learning so much from going through this.

**Comment by davidmezzetti** [comment]
Thank you for the suggestion! Changes made.
