### ISSUE TITLE
including embeddings.py, scoring.py, pipeline.py etc. in cord19q

### ISSUE THREAD

**Issue by DavidRivasPhD** [neuml/cord19q#4]
Hi David,
Thank you for helping us run paperai v1.2.1. successfully. Unfortunately, this version does not include embeddings.py, scoring.py, pipeline.py etc., which significantly improve the results’ quality.
So I tried to install cord19q v2.3.0 because we need to reproduce the high quality results you obtained with previous cord19q versions.  However, I’m getting the following error, which might be due to the recent changes you made to neuml/magnitude
![Screenshot from 2020-08-16 17-31-25](https://user-images.githubusercontent.com/61651965/90356658-80e66180-e00d-11ea-91f0-1254327d4349.png)
Do you think I should try to install cord19q v2.3.0 with a previous version of magnitude (i.e.  neuml/magnitude v0.1.143)?
or would you be able to do something on your side that would allow me to install and run cord19q v2.3.0?

**Comment by davidmezzetti** [comment]
If you want to run v2.3.0, you can change your local copy of setup.py to replace the line:

          "pymagnitude @ git+https://github.com/neuml/magnitude",

with

          "pymagnitude-lite>=0.1.43",

The name change affected the pip package name only, so this should allow you to install an older version to reproduce results.

**Comment by DavidRivasPhD** [comment]
Thank you. The above editions allowed me to install cord19q v2.3.0
